# -*- coding: utf-8 -*-
"""2_classification_by_a_neural_network_using_Keras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKaJiWMx0Nz2t8naqtOQQoVjAgmh2KEA
"""

# Run on google colab

"""**Classification of Palmer Archipelago, Antarctica**"""

import seaborn as sns

penguins = sns.load_dataset('penguins')
penguins.head()

penguins.shape

sns.pairplot(penguins,hue = 'species')

sns.pairplot(penguins, hue = 'sex')

"""**Prepare the data**"""

# drop categorical values
penguins_filtered = penguins.drop(columns = ['island', 'sex'])
penguins_filtered.head()

penguins_filtered = penguins_filtered.dropna()
penguins_filtered.head()

penguins_filtered.shape

# create features
features = penguins_filtered.drop(columns = ['species'])
features.head()

# one hot encoding
import pandas as pd
target = pd.get_dummies(penguins_filtered['species'])
target.head()

"""**Split into train test sets**"""

# split into train/test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target,
                                                   test_size = 0.2,
                                                   random_state = 0,
                                                    shuffle = True,
                                                   stratify = target)
print('train test = ', X_train.shape, X_test.shape, y_train.shape, y_test.shape)

"""**Build neural network architecture**"""

from tensorflow import keras
keras.utils.set_random_seed(42)

# i/p + 1 hidden layer + o/p layer
# input layer
inputs = keras.Input(shape = (X_train.shape[1],))

# hidden layer
hidden_layer = keras.layers.Dense(10,activation='relu')(inputs)

# output layer
output_layer = keras.layers.Dense(3, activation = 'softmax')(hidden_layer)

# assemble model
model = keras.Model(inputs = inputs, outputs = output_layer)
model.summary()

"""**Choice of optimizer and loss function**"""

model.compile(optimizer = 'adam', loss = keras.losses.CategoricalCrossentropy())

"""**Train the model**"""

history = model.fit(X_train, y_train, epochs = 100)

sns.lineplot(x = history.epoch, y = history.history['loss'])

"""**Perform predictions/classification**"""

y_pred = model.predict(X_test)
y_pred.shape

prediction = pd.DataFrame(y_pred, columns=target.columns)
prediction

predicted_species = prediction.idxmax(axis = 'columns')
predicted_species

from sklearn.metrics import confusion_matrix

true_species = y_test.idxmax(axis="columns")

matrix = confusion_matrix(true_species, predicted_species)
print(matrix)

# Convert to a pandas dataframe
confusion_df = pd.DataFrame(matrix, index=y_test.columns.values, columns=y_test.columns.values)

# Set the names of the x and y axis, this helps with the readability of the heatmap.
confusion_df.index.name = 'True Label'
confusion_df.columns.name = 'Predicted Label'
confusion_df.head()

sns.heatmap(confusion_df, annot=True,cmap = 'Blues')

model.layers[1].get_weights()

model.layers[2].get_weights()